"""updated customer id

Revision ID: 0acdf9f722e6
Revises: fe458b92d336
Create Date: 2025-02-26 16:59:28.527609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acdf9f722e6'
down_revision = 'fe458b92d336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('orders_table_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('orders_customer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'table_reservations', ['table_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.alter_column('photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.alter_column('photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_customer_id_fkey', 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key('orders_table_id_fkey', 'table_reservations', ['table_id'], ['id'])
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
