"""Add outlet_id and items columns to orders table

Revision ID: d553d34448f1
Revises: 6467d28a62d1
Create Date: 2025-03-04 10:36:23.754949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd553d34448f1'
down_revision = '6467d28a62d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_outlet_id_fkey', type_='foreignkey')
        batch_op.drop_column('outlet_id')
        batch_op.drop_column('items')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('outlet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_outlet_id_fkey', 'outlets', ['outlet_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
