"""Initial migration

Revision ID: fe458b92d336
Revises: 4d83cb0c8ea7
Create Date: 2025-02-24 02:32:15.738780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe458b92d336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(),
                              nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        # Add new columns with temporary defaults to avoid null values on existing rows.
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False, server_default=sa.text('0')))
        batch_op.alter_column('customer_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('datetime',
                              existing_type=postgresql.TIMESTAMP(),
                              nullable=False)
        batch_op.alter_column('status',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
        batch_op.drop_constraint('orders_tablereservation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('orders_food_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'table_reservations', ['table_id'], ['id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('food_id')
        batch_op.drop_column('tablereservation_id')
        # Remove the temporary server defaults so that future inserts must explicitly provide values.
        batch_op.alter_column('table_id', server_default=None)
        batch_op.alter_column('total', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tablereservation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_food_id_fkey', 'foods', ['food_id'], ['id'])
        batch_op.create_foreign_key('orders_tablereservation_id_fkey', 'table_reservations', ['tablereservation_id'], ['id'])
        batch_op.alter_column('status',
                              existing_type=sa.VARCHAR(),
                              nullable=False)
        batch_op.alter_column('datetime',
                              existing_type=postgresql.TIMESTAMP(),
                              nullable=True)
        batch_op.alter_column('customer_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.drop_column('total')
        batch_op.drop_column('table_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(),
                              nullable=False)
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(),
                              nullable=False)
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(),
                              nullable=False)
    # ### end Alembic commands ###
